In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv('../data/dataframe.csv', index_col = 0)

In [37]:
df.columns

Index(['Unnamed: 0', 'Address', 'Species', 'Block', 'Street', 'Trap',
       'AddressNumberAndStreet', 'Latitude', 'Longitude', 'AddressAccuracy',
       'NumMosquitos', 'WnvPresent', 'Tmax_x', 'Tmin_x', 'Tavg_x', 'Depart_x',
       'DewPoint_x', 'WetBulb_x', 'Heat_x', 'Cool_x', 'Sunrise_x', 'Sunset_x',
       'CodeSum_x', 'Depth_x', 'PrecipTotal_x', 'StnPressure_x', 'SeaLevel_x',
       'ResultSpeed_x', 'ResultDir_x', 'AvgSpeed_x', 'Tmax_y', 'Tmin_y',
       'Tavg_y', 'Depart_y', 'DewPoint_y', 'WetBulb_y', 'Heat_y', 'Cool_y',
       'Sunrise_y', 'Sunset_y', 'CodeSum_y', 'Depth_y', 'PrecipTotal_y',
       'StnPressure_y', 'SeaLevel_y', 'ResultSpeed_y', 'ResultDir_y',
       'AvgSpeed_y', 'Day_length', 'Tavg', 'Day_length_shift', 'Tavg_shift',
       'ResultSpeed_y_shift', 'ResultDir_y_shift', 'AvgSpeed_y_shift',
       'ResultSpeed_x_shift', 'ResultDir_x_shift', 'AvgSpeed_x_shift'],
      dtype='object')

In [38]:
df['PrecipTotal_y'].value_counts()

 0.00    5808
-1.00     857
 0.06     468
 0.01     433
 0.36     305
 0.83     276
 0.02     234
 0.03     204
 0.20     186
 0.13     146
 0.88     139
 0.23     131
 0.92     129
 0.59     127
 0.84     119
 0.11     116
 0.12      93
 0.09      93
 0.19      93
 0.87      93
 0.04      83
 0.44      62
 0.17      61
 0.16      60
 0.27      60
 1.19      54
 0.08      50
 0.46      26
Name: PrecipTotal_y, dtype: int64

In [39]:
df.head()

,Unnamed: 0,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,...,Day_length,Tavg,Day_length_shift,Tavg_shift,ResultSpeed_y_shift,ResultDir_y_shift,AvgSpeed_y_shift,ResultSpeed_x_shift,ResultDir_x_shift,AvgSpeed_x_shift
Date,,,,,,,,,,,,,,,,,,,,,
2007-05-29,0,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,1496,67.240489,NaN,67.240489,8.266667,11.666667,9.933333,8.566667,13.333333,10.433333
2007-05-29,1,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,1496,67.240489,NaN,67.240489,8.266667,11.666667,9.933333,8.566667,13.333333,10.433333
2007-05-29,2,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,...,1496,67.240489,NaN,67.240489,8.266667,11.666667,9.933333,8.566667,13.333333,10.433333
2007-05-29,3,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,1496,67.240489,NaN,67.240489,8.266667,11.666667,9.933333,8.566667,13.333333,10.433333
2007-05-29,4,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,1496,67.240489,NaN,67.240489,8.266667,11.666667,9.933333,8.566667,13.333333,10.433333

In [40]:
df['Day_length']

Date
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-05-29    1496
2007-06-05    1506
2007-06-05    1506
2007-06-05    1506
2007-06-05    1506
2007-06-05    1506
              ...
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
2013-09-26    1199
Name: Day_length, Length: 10506, dtype: int64

In [41]:
df[df.index == '2007-06-05']

,Unnamed: 0,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,...,Day_length,Tavg,Day_length_shift,Tavg_shift,ResultSpeed_y_shift,ResultDir_y_shift,AvgSpeed_y_shift,ResultSpeed_x_shift,ResultDir_x_shift,AvgSpeed_x_shift
Date,,,,,,,,,,,,,,,,,,,,,
2007-06-05,25,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,26,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,27,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,28,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,30,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX PIPIENS/RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,31,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,32,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX PIPIENS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,33,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,34,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS/RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,35,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,36,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,37,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,38,"2100 North Stave Street, Chicago, IL 60647, USA",CULEX PIPIENS/RESTUANS,21,N STAVE ST,T050,"2100 N STAVE ST, Chicago, IL",41.919343,-87.694259,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,39,"2100 North Stave Street, Chicago, IL 60647, USA",CULEX RESTUANS,21,N STAVE ST,T050,"2100 N STAVE ST, Chicago, IL",41.919343,-87.694259,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,40,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,41,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,42,"1700 West 95th Street, Chicago, IL 60643, USA",CULEX PIPIENS/RESTUANS,17,W 95TH ST,T094,"1700 W 95TH ST, Chicago, IL",41.720848,-87.666014,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,43,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX PIPIENS/RESTUANS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,44,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,45,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX PIPIENS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,46,"6500 North Oak Park Avenue, Chicago, IL 60631,...",CULEX PIPIENS/RESTUANS,65,N OAK PARK AVE,T143,"6500 N OAK PARK AVE, Chicago, IL",41.999129,-87.795585,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,47,"6500 North Oak Park Avenue, Chicago, IL 60631,...",CULEX RESTUANS,65,N OAK PARK AVE,T143,"6500 N OAK PARK AVE, Chicago, IL",41.999129,-87.795585,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,48,"1500 North Long Avenue, Chicago, IL 60651, USA",CULEX RESTUANS,15,N LONG AVE,T153,"1500 N LONG AVE, Chicago, IL",41.907645,-87.760886,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,49,"8900 South Carpenter Street, Chicago, IL 60620...",CULEX RESTUANS,89,S CARPENTER ST,T159,"8900 S CARPENTER ST, Chicago, IL",41.732984,-87.649642,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,50,"9100 West Higgins Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,91,W HIGGINS AVE,T009,"9100 W HIGGINS AVE, Chicago, IL",41.981964,-87.812827,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,51,"3600 North Pittsburgh Avenue, Chicago, IL 6063...",CULEX RESTUANS,36,N PITTSBURGH AVE,T011,"3600 N PITTSBURGH AVE, Chicago, IL",41.944869,-87.832763,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,52,"7200 North Oketo Avenue, Chicago, IL 60631, USA",CULEX RESTUANS,72,N OKETO AVE,T016,"7200 N OKETO AVE, Chicago, IL",42.011601,-87.811506,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,53,"3800 North California Avenue, Chicago, IL 6061...",CULEX RESTUANS,38,N CALIFORNIA AVE,T019,"3800 N CALIFORNIA AVE, Chicago, IL",41.949830,-87.698457,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,54,"4900 West Balmoral Avenue, Chicago, IL 60630, USA",CULEX RESTUANS,49,W BALMORAL AVE,T025,"4900 W BALMORAL AVE, Chicago, IL",41.979243,-87.750938,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,55,"5800 North Western Avenue, Chicago, IL 60659, USA",CULEX RESTUANS,58,N WESTERN AVE,T028,"5800 N WESTERN AVE, Chicago, IL",41.986921,-87.689778,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,56,"5000 South Central Avenue, Chicago, IL 60638, USA",CULEX PIPIENS/RESTUANS,50,S CENTRAL AVE,T031,"5000 S CENTRAL AVE, Chicago, IL",41.801498,-87.763416,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,57,"1400 North Sacramento Avenue, Chicago, IL 6062...",CULEX RESTUANS,14,N HUMBOLDT DR,T033,"1400 N HUMBOLDT DR, Chicago, IL",41.906638,-87.701431,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,58,"South Vincennes Avenue, Chicago, IL, USA",CULEX RESTUANS,10,S VINCENNES,T089,"1000 S VINCENNES, Chicago, IL",41.723195,-87.649970,5,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,59,"University of Illinois at Chicago, 1100 South ...",CULEX PIPIENS/RESTUANS,11,S ASHLAND AVE,T090,"1100 S ASHLAND AVE, Chicago, IL",41.868077,-87.666901,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,60,"University of Illinois at Chicago, 1100 South ...",CULEX RESTUANS,11,S ASHLAND AVE,T090,"1100 S ASHLAND AVE, Chicago, IL",41.868077,-87.666901,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,61,"1100 South State Street, Chicago, IL 60605, USA",CULEX PIPIENS/RESTUANS,11,S STATE ST,T092,"1100 S STATE ST, Chicago, IL",41.869216,-87.627561,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,62,"4200 West 127th Street, Alsip, IL 60803, USA",CULEX PIPIENS/RESTUANS,42,W 127TH PL,T135,"4200 W 127TH PL, Chicago, IL",41.662014,-87.724608,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,63,"4200 West 127th Street, Alsip, IL 60803, USA",CULEX RESTUANS,42,W 127TH PL,T135,"4200 W 127TH PL, Chicago, IL",41.662014,-87.724608,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,64,"4200 West 127th Street, Alsip, IL 60803, USA",CULEX PIPIENS,42,W 127TH PL,T135,"4200 W 127TH PL, Chicago, IL",41.662014,-87.724608,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,65,"5300 West Agatite Avenue, Chicago, IL 60630, USA",CULEX PIPIENS/RESTUANS,53,W AGATITE AVE,T141,"5300 W AGATITE AVE, Chicago, IL",41.961743,-87.760070,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,66,"5300 West Agatite Avenue, Chicago, IL 60630, USA",CULEX RESTUANS,53,W AGATITE AVE,T141,"5300 W AGATITE AVE, Chicago, IL",41.961743,-87.760070,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,67,"4000 North Austin Avenue, Chicago, IL 60634, USA",CULEX PIPIENS/RESTUANS,40,N AUSTIN AVE,T142,"4000 N AUSTIN AVE, Chicago, IL",41.953067,-87.776792,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,68,"4000 North Austin Avenue, Chicago, IL 60634, USA",CULEX RESTUANS,40,N AUSTIN AVE,T142,"4000 N AUSTIN AVE, Chicago, IL",41.953067,-87.776792,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,69,"Chicago, IL, USA",CULEX RESTUANS,43,N ASHLAND AVE OVERPASS,T145,"4300 N ASHLAND AVE OVERPASS, Chicago, IL",41.878114,-87.629798,3,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,70,"4200 North Richmond Street, Chicago, IL 60618,...",CULEX PIPIENS/RESTUANS,42,N RICHMOND ST,T146,"4200 N RICHMOND ST, Chicago, IL",41.958271,-87.702575,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,71,"4200 North Richmond Street, Chicago, IL 60618,...",CULEX RESTUANS,42,N RICHMOND ST,T146,"4200 N RICHMOND ST, Chicago, IL",41.958271,-87.702575,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,72,"2800 North Francisco Avenue, Chicago, IL 60618...",CULEX RESTUANS,28,N FRANCISCO AVE,T147,"2800 N FRANCISCO AVE, Chicago, IL",41.932094,-87.700117,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,73,"1500 West Granville Avenue, Chicago, IL 60660,...",CULEX PIPIENS/RESTUANS,15,W GRANVILLE AVE,T149,"1500 W GRANVILLE AVE, Chicago, IL",41.994469,-87.667736,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,74,"1800 West Farwell Avenue, Chicago, IL 60626, USA",CULEX RESTUANS,18,W FARWELL AVE,T150,"1800 W FARWELL AVE, Chicago, IL",42.006858,-87.675919,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,75,"7000 West Armitage Avenue, Chicago, IL 60707, USA",CULEX PIPIENS/RESTUANS,70,W ARMITAGE AVENUE,T151,"7000 W ARMITAGE AVENUE, Chicago, IL",41.916265,-87.800515,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,76,"7000 West Armitage Avenue, Chicago, IL 60707, USA",CULEX RESTUANS,70,W ARMITAGE AVENUE,T151,"7000 W ARMITAGE AVENUE, Chicago, IL",41.916265,-87.800515,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,77,"2500 South Millard Avenue, Chicago, IL 60623, USA",CULEX RESTUANS,25,S MILLARD AVE,T152,"2500 S MILLARD AVE, Chicago, IL",41.846075,-87.716277,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,78,"2100 North Lawler Avenue, Chicago, IL 60639, USA",CULEX RESTUANS,21,N LAWLER AVE,T154,"2100 N LAWLER AVE, Chicago, IL",41.918705,-87.752329,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,79,"3500 West 116th Street, Chicago, IL 60655, USA",CULEX PIPIENS/RESTUANS,35,W 116TH ST,T158,"3500 W 116TH ST, Chicago, IL",41.682587,-87.707973,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,80,"3500 West 116th Street, Chicago, IL 60655, USA",CULEX RESTUANS,35,W 116TH ST,T158,"3500 W 116TH ST, Chicago, IL",41.682587,-87.707973,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,81,9300 South Doctor Martin Luther King Junior Dr...,CULEX PIPIENS/RESTUANS,93,S DR MARTIN LUTHER KING JR DR,T162,"9300 S DR MARTIN LUTHER KING JR DR, Chicago, IL",41.725517,-87.614258,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,82,"3700 North Kedvale Avenue, Chicago, IL 60641, USA",CULEX PIPIENS/RESTUANS,37,N KEDVALE AVE,T218,"3700 N KEDVALE AVE, Chicago, IL",41.948167,-87.730698,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,83,"3700 North Kedvale Avenue, Chicago, IL 60641, USA",CULEX RESTUANS,37,N KEDVALE AVE,T218,"3700 N KEDVALE AVE, Chicago, IL",41.948167,-87.730698,8,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667
2007-06-05,84,"4500 North Campbell Avenue, Chicago, IL 60625,...",CULEX RESTUANS,45,N CAMPBELL AVE,T220,"4500 N CAMPBELL AVE, Chicago, IL",41.963976,-87.691810,9,...,1506,67.240489,NaN,67.240489,9.533333,19.0,11.0,10.533333,20.666667,12.566667

In [42]:
df.index.unique()

Index(['2007-05-29', '2007-06-05', '2007-06-26', '2007-06-29', '2007-07-02',
       '2007-07-11', '2007-07-18', '2007-07-19', '2007-07-25', '2007-07-27',
       '2007-08-01', '2007-08-02', '2007-08-03', '2007-08-07', '2007-08-08',
       '2007-08-09', '2007-08-15', '2007-08-16', '2007-08-17', '2007-08-21',
       '2007-08-22', '2007-08-24', '2007-08-28', '2007-09-04', '2007-09-05',
       '2007-09-06', '2007-09-12', '2007-09-18', '2007-09-19', '2007-09-24',
       '2007-09-25', '2007-10-04', '2007-10-09', '2009-05-28', '2009-06-02',
       '2009-06-03', '2009-06-05', '2009-06-12', '2009-06-15', '2009-06-19',
       '2009-06-22', '2009-06-26', '2009-06-29', '2009-07-06', '2009-07-10',
       '2009-07-13', '2009-07-17', '2009-07-24', '2009-07-27', '2009-07-31',
       '2009-08-07', '2009-08-13', '2009-08-25', '2009-08-27', '2009-09-03',
       '2009-09-14', '2009-09-17', '2009-09-25', '2009-10-01', '2011-06-10',
       '2011-06-17', '2011-06-24', '2011-06-30', '2011-07-11', '2011-07-15',
       '2011-07-25', '2011-07-29', '2011-08-05', '2011-08-12', '2011-08-19',
       '2011-08-26', '2011-09-01', '2011-09-02', '2011-09-12', '2011-09-16',
       '2011-09-23', '2011-09-30', '2013-06-07', '2013-06-14', '2013-06-21',
       '2013-06-27', '2013-06-28', '2013-07-08', '2013-07-12', '2013-07-19',
       '2013-07-25', '2013-08-01', '2013-08-08', '2013-08-15', '2013-08-22',
       '2013-08-29', '2013-09-06', '2013-09-12', '2013-09-19', '2013-09-26'],
      dtype='object', name='Date')

In [43]:
sum(df['Day_length'].isnull())

0