In [1]:
import numpy as np 
import pandas as pd
import pickle

In [2]:
df_test = pd.read_csv('../data/test_final_dataframe_features.csv',index_col=0)

In [3]:
with open('../assets/logistic_regression.pkl', 'rb') as f:
    log_reg = pickle.load(f)

/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

In [4]:
with open('../assets/X_train.pkl', 'rb') as f:
    X_train = pickle.load(f)

In [5]:
test = df_test[X_train.columns]

In [6]:
WNV = log_reg.predict(test)

In [7]:
test['WnvPresent'] = WNV

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [8]:
data = {'WnvPresent': test['WnvPresent']}

In [9]:
submit = pd.DataFrame(data)

In [10]:
submit= submit.set_index(df_test['Id'])

In [11]:
submit.to_csv('../data/submission.csv')

In [12]:
submit

        WnvPresent
Id
1                0
2                0
3                0
4                0
5                0
6                0
7                0
8                0
9                0
10               0
11               0
12               0
13               0
14               0
15               0
16               0
17               0
18               0
19               0
20               0
21               0
22               0
23               0
24               0
25               0
26               0
27               0
28               0
29               0
30               0
...            ...
116264           0
116265           0
116266           0
116267           0
116268           0
116269           0
116270           0
116271           0
116272           0
116273           0
116274           0
116275           0
116276           0
116277           0
116278           0
116279           0
116280           0
116281           0
116282           0
116283           0
116284           0
116285           0
116286           0
116287           0
116288           0
116289           0
116290           0
116291           0
116292           0
116293           0

[116293 rows x 1 columns]